name: Daily Wavelet NO Run

on:
  schedule:
    - cron: '23 00 * * 1-6'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python trainer.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
